// Willian Hiroshi da Silva Fukuda Gardini - 2209624

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author wwwil
 */
public class PokedexEletrico extends javax.swing.JFrame {
    private EletricoPokemon e1 = new EletricoPokemon();
    
    private GerEletrico ge = GerEletrico.geraGerEletrico();
    
    private static PokedexEletrico pokUnic;
    /**
     * Creates new form Pokedex
     */
    private PokedexEletrico() {
        initComponents();
    }

    public static PokedexEletrico geraPokedexEletrico(){
        if(pokUnic == null){
            pokUnic = new PokedexEletrico();
        }
        return pokUnic;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cxNivel = new javax.swing.JTextField();
        cxCargaDeRaio = new javax.swing.JRadioButton();
        cxDescarga = new javax.swing.JRadioButton();
        cxRelampagoFulminante = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btCadastrar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome:");

        cxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Nivel:");

        buttonGroup1.add(cxCargaDeRaio);
        cxCargaDeRaio.setText("Carga de Raio");
        cxCargaDeRaio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCargaDeRaioActionPerformed(evt);
            }
        });

        buttonGroup1.add(cxDescarga);
        cxDescarga.setText("Descarga");

        buttonGroup1.add(cxRelampagoFulminante);
        cxRelampagoFulminante.setText("Relampago Fulminante");

        jLabel3.setText("Ataque:");

        jLabel4.setText("Informações Pokemon Eletrico");

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxNome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btConsultar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btAlterar)))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cxCargaDeRaio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxDescarga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxRelampagoFulminante)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(173, 173, 173))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxDescarga)
                    .addComponent(cxRelampagoFulminante)
                    .addComponent(cxCargaDeRaio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btExcluir)
                    .addComponent(btAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConsultar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxCargaDeRaioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCargaDeRaioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCargaDeRaioActionPerformed

    private void cxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluirPok();        // TODO add your handling code here:
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        alterarPok();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultaPok();
    }//GEN-LAST:event_btConsultarActionPerformed
    
    public void cadastrar() {
    try {
        validarNome(cxNome.getText());
        validarNivel(cxNivel.getText());

        e1 = new EletricoPokemon();
        e1.setNome(cxNome.getText());
        e1.setNivel(Integer.parseInt(cxNivel.getText()));

        if (cxCargaDeRaio.isSelected()) {
            e1.setCargaDeRaio("Carga de Raio");
            e1.setPoder("Carga de Raio");
        } else if (cxDescarga.isSelected()) {
            e1.setDescarga("Descarga");
            e1.setPoder("Descarga");
        } else if (cxRelampagoFulminante.isSelected()) {
            e1.setRelampagoFulminante("Relâmpago Fulminante");
            e1.setPoder("Relâmpago Fulminante");
        }

        e1 = ge.cadasPok(e1);

        if (e1 != null) {
            JOptionPane.showMessageDialog(null, "Pokemon Elétrico cadastrado com sucesso!", "Cadastro de Pokemons Elétricos", 1);
        } else {
            JOptionPane.showMessageDialog(null, "Pokemon já Existente!", "Cadastro de Pokemons Elétricos", 0);
        }
    } catch (NomeInvalidoException | NivelInvalidoException e) {
        JOptionPane.showMessageDialog(null, e.getMessage(), "Erro de Validacão", JOptionPane.ERROR_MESSAGE);
    }
}

public void excluirPok() {
    try {
        validarNome(cxNome.getText());

        e1 = new EletricoPokemon();
        e1.setNome(cxNome.getText());

        e1 = ge.delPokNivel(e1);

        if (e1 == null) {
            JOptionPane.showMessageDialog(null, "Dados excluídos com sucesso!", "EXCLUSÃO DE DADOS", 1);
        } else {
            JOptionPane.showMessageDialog(null, "Pokemon Elétrico INEXISTENTE", "EXCLUSÃO DE DADOS", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NomeInvalidoException e) {
        JOptionPane.showMessageDialog(null, e.getMessage(), "Erro de Validacão", JOptionPane.ERROR_MESSAGE);
        cxNome.requestFocus();
    }
}

public void alterarPok() {
    try {
        validarNivel(cxNivel.getText());

        e1 = new EletricoPokemon();
        e1.setNivel(Integer.parseInt(cxNivel.getText()));

        e1 = ge.atualizaPokNivel(e1);

        if (e1 != null) {
            cxNivel.setText(Integer.toString(e1.getNivel()));
            cxNome.setText(e1.getNome());

            JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!", "ALTERAÇÃO DE DADOS", 1);

        } else {
            JOptionPane.showMessageDialog(null, "CPF inexistente", "ALTERAÇÃO DE DADOS", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NivelInvalidoException e) {
        JOptionPane.showMessageDialog(null, e.getMessage(), "Erro de Validacão", JOptionPane.ERROR_MESSAGE);
        cxNivel.requestFocus();
    }
}

public void consultaPok() {
    try {
        validarNome(cxNome.getText());

        e1 = new EletricoPokemon();
        e1.setNome(cxNome.getText());

        e1 = ge.consPokNome(e1);

        if (e1 != null) {
            cxNivel.setText(Integer.toString(e1.getNivel()));
            cxNome.setText(e1.getNome());

            if (e1.getCargaDeRaio().equalsIgnoreCase("Carga de Raio")) {
                cxCargaDeRaio.setSelected(true);
            } else if (e1.getDescarga().equalsIgnoreCase("Descarga")) {
                cxDescarga.setSelected(true);
            } else {
                cxRelampagoFulminante.setSelected(true);
            }

            JOptionPane.showMessageDialog(null, "Confira os dados", "CONSULTA DE POKEMON", 1);
        } else {
            JOptionPane.showMessageDialog(null, "Pokemon inexistente!", "CONSULTA DE POKEMON", 0);
        }
    } catch (NomeInvalidoException e) {
        JOptionPane.showMessageDialog(null, e.getMessage(), "Erro de Validacão", JOptionPane.ERROR_MESSAGE);
        cxNome.requestFocus();
    }
}


    private void validarNome(String nome) throws NomeInvalidoException {
        if (!nome.matches("[a-zA-Z]+")) {
            throw new NomeInvalidoException("O nome deve conter apenas letras.");
        }
    }

    private void validarNivel(String nivel) throws NivelInvalidoException {
        try {
            Integer.parseInt(nivel);
        } catch (NumberFormatException e) {
            throw new NivelInvalidoException("O nível deve ser um número inteiro.");
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokedexAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokedexAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokedexAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokedexAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PokedexEletrico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btExcluir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cxCargaDeRaio;
    private javax.swing.JRadioButton cxDescarga;
    private javax.swing.JTextField cxNivel;
    private javax.swing.JTextField cxNome;
    private javax.swing.JRadioButton cxRelampagoFulminante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
