// Willian Hiroshi da Silva Fukuda Gardini - 2209624

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author wwwil
 */
public class PokedexFogo extends javax.swing.JFrame {;
    private FogoPokemon f1 = new FogoPokemon();
    
    private GerFogo gf = GerFogo.geraGerFogo();
    
    private static PokedexFogo pokUnic;
    /**
     * Creates new form Pokedex
     */
    private PokedexFogo() {
        initComponents();
    }

    public static PokedexFogo geraPokedexFogo(){
        if(pokUnic == null){
            pokUnic = new PokedexFogo();
        }
        return pokUnic;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cxNivel = new javax.swing.JTextField();
        cxErupcao = new javax.swing.JRadioButton();
        cxQueimadura = new javax.swing.JRadioButton();
        cxChute = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btCadastrar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome:");

        cxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Nivel:");

        buttonGroup1.add(cxErupcao);
        cxErupcao.setText("Erupção");
        cxErupcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxErupcaoActionPerformed(evt);
            }
        });

        buttonGroup1.add(cxQueimadura);
        cxQueimadura.setText("Queimadura Explosiva");

        buttonGroup1.add(cxChute);
        cxChute.setText("Chute Labareda");

        jLabel3.setText("Ataque:");

        jLabel4.setText("Informações Pokemon de Fogo");

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btConsultar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btAlterar)))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cxErupcao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxQueimadura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxChute)
                        .addGap(19, 19, 19))))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxNome))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxQueimadura)
                    .addComponent(cxChute)
                    .addComponent(cxErupcao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar)
                    .addComponent(btExcluir)
                    .addComponent(btAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConsultar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxErupcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxErupcaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxErupcaoActionPerformed

    private void cxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        excluirPok();        // TODO add your handling code here:
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        alterarPok();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultaPok();
    }//GEN-LAST:event_btConsultarActionPerformed

    public void cadastrar() {
        try {
            validarNome(cxNome.getText());
            validarNivel(cxNivel.getText());

            f1 = new FogoPokemon();
            f1.setNome(cxNome.getText());
            f1.setNivel(Integer.parseInt(cxNivel.getText()));

           if (cxQueimadura.isSelected()) {
                f1.setQueimaduraExplosiva("Queimadura Explosiva");
                f1.setPoder("Queimadura Explosiva");
            } else if (cxChute.isSelected()) {
                f1.setChuteLabareda("Chute Labareda");
                f1.setPoder("Chute Labareda");
            } else if (cxErupcao.isSelected()) {
                f1.setErupcao("Erupção");
                f1.setPoder("Erupção");
            }

            f1 = gf.cadasPok(f1);

            if (f1 != null) {
                JOptionPane.showMessageDialog(null, "Pokemon de Fogo cadastrado com sucesso!", "Cadastro de Pokemons de Fogo", 1);
            } else {
                JOptionPane.showMessageDialog(null, "Pokemon já Existente!", "Cadastro de Pokemons de Fogo", 0);
            }
        } catch (NomeInvalidoException | NivelInvalidoException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro de Validacão", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void excluirPok() {
        try {
            validarNome(cxNome.getText());

            f1 = new FogoPokemon();
            f1.setNome(cxNome.getText());

            f1 = gf.delPokNivel(f1);

            if (f1 == null) {
                JOptionPane.showMessageDialog(null, "Dados excluídos com sucesso!", "EXCLUSÃO DE DADOS", 1);
            } else {
                JOptionPane.showMessageDialog(null, "Pokemon de Fogo INEXISTENTE", "EXCLUSÃO DE DADOS", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NomeInvalidoException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro de Validacão", JOptionPane.ERROR_MESSAGE);
            cxNome.requestFocus();
        }
    }

    public void alterarPok() {
        try {
            validarNivel(cxNivel.getText());

            f1 = new FogoPokemon();
            f1.setNivel(Integer.parseInt(cxNivel.getText()));

            f1 = gf.atualizaPokNivel(f1);

            if (f1 != null) {
                cxNivel.setText(Integer.toString(f1.getNivel()));
                cxNome.setText(f1.getNome());

                JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!", "ALTERAÇÃO DE DADOS", 1);

            } else {
                JOptionPane.showMessageDialog(null, "CPF inexistente", "ALTERAÇÃO DE DADOS", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NivelInvalidoException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro de Validacão", JOptionPane.ERROR_MESSAGE);
            cxNivel.requestFocus();
        }
    }

    public void consultaPok() {
        try {
            validarNome(cxNome.getText());

            f1 = new FogoPokemon();
            f1.setNome(cxNome.getText());

            f1 = gf.consPokNome(f1);

            if (f1 != null) {

                cxNivel.setText(Integer.toString(f1.getNivel()));
                cxNome.setText(f1.getNome());

                if (f1.getQueimaduraExplosiva().equalsIgnoreCase("Queimadura Explosiva")) {
                    cxQueimadura.setSelected(true);
                } else if (f1.getChuteLabareda().equalsIgnoreCase("Chute Labareda")) {
                    cxChute.setSelected(true);
                } else {
                    cxErupcao.setSelected(true);
                }

                JOptionPane.showMessageDialog(null, "Confira os dados", "CONSULTA DE POKEMON", 1);
            } else {
                JOptionPane.showMessageDialog(null, "Pokemon inexistente!", "CONSULTA DE POKEMON", 0);
            }
        } catch (NomeInvalidoException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro de Validacão", JOptionPane.ERROR_MESSAGE);
            cxNome.requestFocus();
        }
    }

    private void validarNome(String nome) throws NomeInvalidoException {
            if (!nome.matches("[a-zA-Z]+")) {
                throw new NomeInvalidoException("O nome deve conter apenas letras.");
            }
        }

        private void validarNivel(String nivel) throws NivelInvalidoException {
            try {
                Integer.parseInt(nivel);
            } catch (NumberFormatException e) {
                throw new NivelInvalidoException("O nível deve ser um número inteiro.");
            }
    }


    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokedexAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokedexAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokedexAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokedexAgua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PokedexFogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btExcluir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cxChute;
    private javax.swing.JRadioButton cxErupcao;
    private javax.swing.JTextField cxNivel;
    private javax.swing.JTextField cxNome;
    private javax.swing.JRadioButton cxQueimadura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
